// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhenIsRelease.Data.Models.Context;

namespace WhenIsRelease.Data.Migrations.Game
{
    [DbContext(typeof(GameContext))]
    partial class GameContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("game")
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WhenIsRelease.Data.Models.GameReleases.GameRelease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image");

                    b.Property<DateTime>("LastUpdate");

                    b.Property<string>("Name");

                    b.Property<int?>("PlatformId");

                    b.Property<int?>("RegionId");

                    b.Property<DateTime>("ReleaseDate");

                    b.Property<int>("SourceId");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("PlatformId");

                    b.HasIndex("RegionId");

                    b.ToTable("GameRelease");
                });

            modelBuilder.Entity("WhenIsRelease.Data.Models.GameReleases.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abbreviation");

                    b.Property<string>("Image");

                    b.Property<DateTime>("LastUpdate");

                    b.Property<string>("Name");

                    b.Property<int>("SourceId");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("Platform");
                });

            modelBuilder.Entity("WhenIsRelease.Data.Models.GameReleases.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image");

                    b.Property<DateTime>("LastUpdate");

                    b.Property<string>("Name");

                    b.Property<int>("SourceId");

                    b.HasKey("Id");

                    b.ToTable("Region");
                });

            modelBuilder.Entity("WhenIsRelease.Data.Models.GameReleases.GameRelease", b =>
                {
                    b.HasOne("WhenIsRelease.Data.Models.GameReleases.Platform", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformId");

                    b.HasOne("WhenIsRelease.Data.Models.GameReleases.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId");
                });
#pragma warning restore 612, 618
        }
    }
}
